AWSTemplateFormatVersion: '2010-09-09'
Description: 'NBC Secret Service'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - stage
      - prod
  InputApplicationTagName:
    Description: Tag used for the resources.
    Type: String
    Default: "mam-secret-userpool-tag"
  InputUserPoolName:
    Description: Name of UserPool resource.
    Type: String
    Default: "mam-secret-userpool"
  InputRefreshTokenValidity:
    Description: The time limit in days refresh token is valid.
    Type: String
    Default: 30
  InputClientName:
    Description: The app client name that containts the client id/secret.
    Type: String
    Default: "mam-secret"

Resources:
   UserPoolResource:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName:
        Ref: InputUserPoolName
      UserPoolTags:
        application:
          Ref: InputApplicationTagName
  UserPoolClientResource:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      AllowedOAuthFlows:
      - client_credentials
      GenerateSecret: 'true'
      ClientName:
        Ref: InputClientName
      PreventUserExistenceErrors: ENABLED
      RefreshTokenValidity:
        Ref: InputRefreshTokenValidity
      SupportedIdentityProviders:
      - COGNITO
      AllowedOAuthScopes:
      - Fn::Join:
        - "/"
        - - Ref: InputUserPoolName
          - read_secret_operation
      - Fn::Join:
        - "/"
        - - Ref: InputUserPoolName
          - create_secret_operation
      - Fn::Join:
        - "/"
        - - Ref: InputUserPoolName
          - delete_secret_operation
      UserPoolId:
        Ref: UserPoolResource
    DependsOn:
    - UserPoolResourceServerResource
  UserPoolResourceServerResource:
    Type: AWS::Cognito::UserPoolResourceServer
    Properties:
      UserPoolId:
        Ref: UserPoolResource
      Identifier:
        Ref: InputUserPoolName
      Name:
        Ref: InputUserPoolName
      Scopes:
      - ScopeName: read_secret_operation
        ScopeDescription: read operation
      - ScopeName: create_secret_operation
        ScopeDescription: create operation
      - ScopeName: delete_secret_operation
        ScopeDescription: delete operation
  UserPoolDomainResource:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Join [ "-", [Ref: InputUserPoolName, Ref: Environment]]
      UserPoolId:
        Ref: UserPoolResource
Outputs:
  UserPoolARN:
    Value:
      Fn::GetAtt:
      - UserPoolResource
      - Arn
  UserPoolProviderURL:
    Value:
      Fn::GetAtt:
      - UserPoolResource
      - ProviderURL
  UserPoolProviderName:
    Value:
      Fn::GetAtt:
      - UserPoolResource
      - ProviderName
  UserPoolID:
    Value:
      Ref: UserPoolResource
